### ISSUE TITLE
Arity checking

### ISSUE THREAD

**Issue by shnarazk** [shnarazk/uiua#2]
https://uiua.org/pad?src=QSDihpAgKDsuLikKQSDiiJ4KIm9rOiBubyBzaWduYXR1cmUiCgpCIOKGkCAofDEuMiA7Li4pCkIg4oieCiJvazogc2lnbmF0dXJlIHwxLjIiCgpGIOKGkCAoO-KNpS4gMikKRiDiiJ4KIm9rOiByZXBlYXQgdy9vIHNpZ25hdHVyZSIKCkcg4oaQICh8MS4yIDvijaUuIDIpCkcg4oieCiJ3aWVyZCBlcnJvciBtZXNzYWdlIg==

https://github.com/uiua-lang/uiua/issues/45

**Comment by kaikalii** [comment]
I have fixed this in a [main repo commit](https://github.com/uiua-lang/uiua/commit/08734705aeede2cb709c273a215c90f0614cba67).
